name: Test and Lint application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Test with pytest
        run: pytest main.py
      
      - name: Lint with pylint
        run: pylint main.py
        
